export const GET_PRODUCTS_BY_ARRIVAL_SUCCESS = 'GET_PRODUCTS_BY_ARRIVAL_SUCCESS'
export const GET_PRODUCTS_BY_ARRIVAL_FAIL = 'GET_PRODUCTS_BY_ARRIVAL_FAIL'

export const GET_PRODUCTS_BY_SELL_SUCCESS = 'GET_PRODUCTS_BY_SELL_SUCCESS'
export const GET_PRODUCTS_BY_SELL_FAIL = 'GET_PRODUCTS_BY_SELL_FAIL'

export const GET_WOODS_SUCCESS = 'GET_WOODS_SUCCESS'
export const GET_WOODS_FAIL = 'GET_WOODS_FAIL'

export const GET_BRANDS_SUCCESS = 'GET_BRANDS_SUCCESS'
export const GET_BRANDS_FAIL = 'GET_BRANDS_FAIL'

export const GET_PRODUCTS_TO_SHOP_SUCCESS = 'GET_PRODUCTS_TO_SHOP_SUCCESS'
export const GET_PRODUCTS_TO_SHOP_FAIL = 'GET_PRODUCTS_TO_SHOP_FAIL'
