export const GET_PRODUCTS_BY_ARRIVAL_SUCCESS = 'GET_PRODUCTS_BY_ARRIVAL_SUCCESS'
export const GET_PRODUCTS_BY_ARRIVAL_FAIL = 'GET_PRODUCTS_BY_ARRIVAL_FAIL'

export const GET_PRODUCTS_BY_SELL_SUCCESS = 'GET_PRODUCTS_BY_SELL_SUCCESS'
export const GET_PRODUCTS_BY_SELL_FAIL = 'GET_PRODUCTS_BY_SELL_FAIL'

export const GET_WOODS_SUCCESS = 'GET_WOODS_SUCCESS'
export const GET_WOODS_FAIL = 'GET_WOODS_FAIL'

export const GET_BRANDS_SUCCESS = 'GET_BRANDS_SUCCESS'
export const GET_BRANDS_FAIL = 'GET_BRANDS_FAIL'

export const ADD_BRAND_SUCCESS = 'ADD_BRAND_SUCCESS'
export const ADD_BRAND_FAIL = 'ADD_BRAND_FAIL'

export const ADD_WOOD_SUCCESS = 'ADD_WOOD_SUCCESS'
export const ADD_WOOD_FAIL = 'ADD_WOOD_FAIL'

export const GET_PRODUCTS_TO_SHOP_SUCCESS = 'GET_PRODUCTS_TO_SHOP_SUCCESS'
export const GET_PRODUCTS_TO_SHOP_FAIL = 'GET_PRODUCTS_TO_SHOP_FAIL'

export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS'
export const CLEAR_PRODUCT = 'CLEAR_PRODUCT'
