export const GET_PRODUCTS_BY_ARRIVAL_SUCCESS = 'GET_PRODUCTS_BY_ARRIVAL_SUCCESS'
export const GET_PRODUCTS_BY_ARRIVAL_FAIL = 'GET_PRODUCTS_BY_ARRIVAL_FAIL'

export const GET_PRODUCTS_BY_SELL_SUCCESS = 'GET_PRODUCTS_BY_SELL_SUCCESS'
export const GET_PRODUCTS_BY_SELL_FAIL = 'GET_PRODUCTS_BY_SELL_FAIL'
