export const SITE_GET_DATA_SUCCESS = 'SITE_GET_DATA_SUCCESS'
export const SITE_GET_DATA_FAIL = 'SITE_GET_DATA_FAIL'

export const SITE_UPDATE_DATA_SUCCESS = 'SITE_UPDATE_DATA_SUCCESS'
export const SITE_UPDATE_DATA_FAIL = 'SITE_UPDATE_DATA_FAIL'

export const SITE_RESET_SUCCESS_UPDATE_SUCCESS =
  'SITE_RESET_SUCCESS_UPDATE_SUCCESS'
