export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGIN_FAIL_RESET = 'USER_LOGIN_FAIL_RESET'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'
export const USER_REGISTER_FAIL_RESET = 'USER_REGISTER_FAIL_RESET'
export const USER_REGISTER_SUCCESS_RESET = 'USER_REGISTER_SUCCESS_RESET'

export const USER_AUTH_REQUEST = 'USER_AUTH_REQUEST'
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS'
export const USER_AUTH_FAIL = 'USER_AUTH_FAIL'
export const USER_LOGIN_LOADING_RESET = 'USER_LOGIN_LOADING_RESET'

export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST'
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS'
export const USER_LOGOUT_FAIL = 'USER_LOGOUT_FAIL'

export const USER_ADD_TO_CART_SUCCESS = 'USER_ADD_TO_CART_SUCCESS'
export const USER_ADD_TO_CART_FAIL = 'USER_ADD_TO_CART_FAIL'

export const USER_GET_CART_ITEMS_SUCCESS = 'USER_GET_CART_ITEMS_SUCCESS'
export const USER_GET_CART_ITEMS_FAIL = 'USER_GET_CART_ITEMS_FAIL'

export const USER_CLEAR_CART_DETAILS = 'USER_CLEAR_CART_DETAILS'

export const USER_REMOVE_CART_ITEM_SUCCESS = 'USER_REMOVE_CART_ITEM_SUCCESS'
export const USER_REMOVE_CART_ITEM_FAIL = 'USER_REMOVE_CART_ITEM_FAIL'

export const USER_BUY_SUCCESS = 'USER_BUY_SUCCESS'
export const USER_BUY_FAIL = 'USER_BUY_FAIL'

export const USER_UPDATE_DATA_SUCCESS = 'USER_UPDATE_DATA_SUCCESS'
export const USER_UDATE_DATA_FAIL = 'USER_UDATE_DATA_FAIL'

export const USER_CLEAR_UPDATE_FORM_SUCCESS = 'USER_CLEAR_UPDATE_FORM_SUCCESS'
